### ISSUE TITLE
import error   : libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by m946107011** [awslabs/autogluon#655]
I use  this two code to install gpu autogluon 
python3 -m pip install -U --pre "mxnet_cu102>=1.7.0b20200713, <2.0.0" -f https://sxjscience.github.io/KDD2020/
python3 -m pip install autogluon

but when i import autogluon 
from autogluon import TabularPrediction as task
i got this error   libcudart.so.10.2: cannot open shared object file: No such file or directory

my enviroment:
ubuntu 20.04
python 3,8
cuda 10.2

please help me 
thanks a lot

**Comment by sxjscience** [comment]
This looks like an issue related to CUDA version. Would you check the CUDA version again? For example, you may run 
```bash
ls -al /usr/local/cuda
```

Also, you may try to install mxnet via `pip install mxnet_cu102==1.7.0` and try again.

**Comment by m946107011** [comment]
> This looks like an issue related to CUDA version. Would you check the CUDA version again? For example, you may run
> 
> ```shell
> ls -al /usr/local/cuda
> ```
> 
> Also, you may try to install mxnet via `pip install mxnet_cu102==1.7.0` and try again.

thanks for reply 
I am sure about my cuda version 
and i have already reinstall with ur suggestion 
but still not work....

**Comment by Renesis88** [comment]
Hi firstly, AutoGluon is not compatible with Python 3.8, only 3.6 and 3.7 supported. So  you should create a separate venv environment to run it.

As for Cuda, I am not sure but I have installed version 10.1 and it works for me.
